apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
- name: hello-gitops
  newName: docker.io/ooocamel/hello-gitops
  newTag: 35f6389b14133ddc7600decf338016cf6b06545a
- name: hello-gitops-app
  newName: docker.io/ooocamel/hello-gitops
  newTag: e8d7e7287928e458f0976ea777094206f5020bb5
